name: cityhive

services:
  cityhive_db:
    image: ghcr.io/cloudnative-pg/postgis:16-3.4
    platform: linux/amd64
    container_name: cityhive_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cityhive
      POSTGRES_USER: cityhive
      POSTGRES_PASSWORD: cityhive
    mem_limit: 256M
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      cityhive:
        aliases:
          - cityhive-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  cityhive:
    driver: bridge

volumes:
  pgdata:
    driver: local
