[project]
name = "cityhive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp-jinja2>=1.6",
    "aiohttp[speedups]>=3.12.7",
    "asyncpg>=0.30.0",
    "pyyaml>=6.0.2",
    "sqlalchemy[asyncio]>=2.0.41",
    "trafaret-config>=2.0.2",
]

[dependency-groups]
dev = ["ruff>=0.11.12"]
testing = [
    "coverage[toml]>=7.8.2",
    "pytest>=8.4.0",
    "pytest-aiohttp>=1.1.0",
    "pytest-asyncio>=1.0.0",
]
